import 'dart:io';
import 'package:flutter/material.dart';
import 'package:geocoding/geocoding.dart';
import 'package:geolocator/geolocator.dart';
import 'package:image_picker/image_picker.dart';
import 'package:myapp/src/data/repositories/post_repository.dart';
import 'package:myapp/src/domain/entities/post.dart';
import 'package:myapp/src/domain/entities/user.dart';
import 'package:provider/provider.dart';

class CreatePostScreen extends StatefulWidget {
  const CreatePostScreen({super.key});

  @override
  State<CreatePostScreen> createState() => _CreatePostScreenState();
}

class _CreatePostScreenState extends State<CreatePostScreen> {
  final _formKey = GlobalKey<FormState>();

  // Controllers
  final _productController = TextEditingController();
  final _brandController = TextEditingController();
  final _storeController = TextEditingController();
  final _originalPriceController = TextEditingController();
  final _finalPriceController = TextEditingController();
  final _otherPromotionController = TextEditingController();

  // State
  String _autoGeneratedDescription = "";
  String? _selectedCategory;
  String? _selectedPromotionType;
  String? _lastEditedPriceField;
  File? _imageFile;
  String _locationName = "Obteniendo ubicación...";
  double _latitude = 0.0;
  double _longitude = 0.0;
  bool _isLoading = false;

  final List<String> _categories = [
    "Alimentos", "Tecnología", "Moda", "Deportes", "Construcción",
    "Animales", "Electrodomésticos", "Servicios", "Educación",
    "Juguetes", "Vehículos", "Otros",
  ];

  final List<String> _promotionTypes = [
    "2x1", "3x1", "3x2", "25% OFF", "30% OFF", "50% OFF",
    "Liquidación", "Otros",
  ];

  @override
  void initState() {
    super.initState();
    _productController.addListener(_updateDescription);
    _brandController.addListener(_updateDescription);
    _otherPromotionController.addListener(_updateDescription);
    _originalPriceController.addListener(() => _lastEditedPriceField = 'original');
    _finalPriceController.addListener(() => _lastEditedPriceField = 'final');
    _getCurrentLocation();
  }

  @override
  void dispose() {
    _productController.dispose();
    _brandController.dispose();
    _storeController.dispose();
    _originalPriceController.dispose();
    _finalPriceController.dispose();
    _otherPromotionController.dispose();
    super.dispose();
  }

  void _updateDescription() {
    setState(() {
      final promotionDetail = _selectedPromotionType == "Otros"
          ? _otherPromotionController.text
          : _selectedPromotionType ?? "";
      final productText = _productController.text;
      final brandText = _brandController.text.isNotEmpty ? "de ${_brandController.text}" : "";

      if (promotionDetail.isNotEmpty || productText.isNotEmpty || brandText.isNotEmpty) {
        _autoGeneratedDescription = "$promotionDetail en $productText $brandText".trim().replaceAll(RegExp(r'\s+'), ' ');
      } else {
        _autoGeneratedDescription = "";
      }
    });
  }

  Future<void> _getCurrentLocation() async {
    bool serviceEnabled;
    LocationPermission permission;

    serviceEnabled = await Geolocator.isLocationServiceEnabled();
    if (!serviceEnabled) {
      if(mounted) setState(() => _locationName = "Servicio de ubicación deshabilitado.");
      return;
    }

    permission = await Geolocator.checkPermission();
    if (permission == LocationPermission.denied) {
      permission = await Geolocator.requestPermission();
      if (permission == LocationPermission.denied) {
        if(mounted) setState(() => _locationName = "Permiso de ubicación denegado.");
        return;
      }
    }

    if (permission == LocationPermission.deniedForever) {
      if(mounted) setState(() => _locationName = "Permiso de ubicación denegado permanentemente.");
      return;
    }

    try {
      final position = await Geolocator.getCurrentPosition();
      final placemarks = await placemarkFromCoordinates(position.latitude, position.longitude);
      
      if (mounted && placemarks.isNotEmpty) {
        final place = placemarks.first;
        setState(() {
          _latitude = position.latitude;
          _longitude = position.longitude;
          _locationName = place.locality ?? place.subAdministrativeArea ?? "Ubicación desconocida";
        });
      }
    } catch (e) {
      if(mounted) setState(() => _locationName = "Error al obtener la ubicación.");
    }
  }

  Future<void> _pickImage() async {
    if (!mounted) return;
    final source = await showDialog<ImageSource>(
      context: context,
      builder: (context) => AlertDialog(
        title: const Text("Seleccionar Imagen"),
        content: const Text("¿Desde dónde quieres obtener la imagen?"),
        actions: [
          TextButton(onPressed: () => Navigator.pop(context, ImageSource.camera), child: const Text("Cámara")),
          TextButton(onPressed: () => Navigator.pop(context, ImageSource.gallery), child: const Text("Galería")),
        ],
      ),
    );

    if (source == null) {
      return;
    }

    final pickedFile = await ImagePicker().pickImage(source: source);
    if (pickedFile != null) {
      setState(() => _imageFile = File(pickedFile.path));
    }
  }

  void _calculatePrices() {
    if (_selectedPromotionType == "Liquidación" || _selectedPromotionType == "Otros" || _selectedPromotionType == null) {
      return;
    }

    if (_lastEditedPriceField == 'original') {
      final priceDouble = double.tryParse(_originalPriceController.text);
      if (priceDouble != null) {
        double? newFinalPrice;
        switch (_selectedPromotionType) {
          case "2x1": newFinalPrice = priceDouble / 2; break;
          case "3x1": newFinalPrice = priceDouble / 3; break;
          case "3x2": newFinalPrice = priceDouble * 2 / 3; break;
          case "25% OFF": newFinalPrice = priceDouble * 0.75; break;
          case "30% OFF": newFinalPrice = priceDouble * 0.70; break;
          case "50% OFF": newFinalPrice = priceDouble * 0.50; break;
        }
        if (newFinalPrice != null) {
          _finalPriceController.text = newFinalPrice.toStringAsFixed(2);
        }
      }
    } else if (_lastEditedPriceField == 'final') {
      final finalPriceDouble = double.tryParse(_finalPriceController.text);
      if (finalPriceDouble != null) {
        double? newOriginalPrice;
        switch (_selectedPromotionType) {
          case "2x1": newOriginalPrice = finalPriceDouble * 2; break;
          case "3x1": newOriginalPrice = finalPriceDouble * 3; break;
          case "3x2": newOriginalPrice = finalPriceDouble * 3 / 2; break;
          case "25% OFF": newOriginalPrice = finalPriceDouble / 0.75; break;
          case "30% OFF": newOriginalPrice = finalPriceDouble / 0.70; break;
          case "50% OFF": newOriginalPrice = finalPriceDouble / 0.50; break;
        }
        if (newOriginalPrice != null) {
          _originalPriceController.text = newOriginalPrice.toStringAsFixed(2);
        }
      }
    }
  }

  Future<void> _submitPost() async {
    if (!mounted) return;

    if (!_formKey.currentState!.validate() || _imageFile == null) {
      ScaffoldMessenger.of(context).showSnackBar(
        const SnackBar(content: Text('Por favor, completa todos los campos y selecciona una imagen.')),
      );
      return;
    }

    setState(() => _isLoading = true);

    try {
      final postRepo = Provider.of<PostRepository>(context, listen: false);
      final currentUser = Provider.of<User?>(context, listen: false);

      if (currentUser == null) {
        throw Exception("No hay un usuario autenticado para crear una publicación.");
      }

      final newPost = Post(
        id: '', // Firestore generará el ID
        user: currentUser,
        description: _autoGeneratedDescription,
        imageUrl: '', // Cloudinary la generará
        location: _locationName,
        latitude: _latitude,
        longitude: _longitude,
        category: _selectedCategory!,
        price: double.parse(_originalPriceController.text),
        discountPrice: double.parse(_finalPriceController.text),
        store: _storeController.text.isNotEmpty ? _storeController.text : "desconocido",
        status: 'activa',
        scores: [],
      );

      await postRepo.addPost(post: newPost, imageFile: _imageFile!);

      if (mounted) {
        ScaffoldMessenger.of(context).showSnackBar(
          const SnackBar(content: Text('¡Oferta publicada con éxito!')),
        );
        Navigator.of(context).pop();
      }
    } catch (e) {
      if (mounted) {
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(content: Text('Error al publicar la oferta: ${e.toString()}')),
        );
      }
    } finally {
      if (mounted) {
        setState(() => _isLoading = false);
      }
    }
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: const Text("Crear Nueva Oferta")),
      body: Stack(
        children: [
          Form(
            key: _formKey,
            child: SingleChildScrollView(
              padding: const EdgeInsets.all(16.0),
              child: Column(
                crossAxisAlignment: CrossAxisAlignment.stretch,
                children: [
                  const Text("Descripción", style: TextStyle(fontWeight: FontWeight.bold)),
                  Card(
                    elevation: 0,
                    color: Colors.grey.shade200,
                    child: Padding(
                      padding: const EdgeInsets.all(12.0),
                      child: Text(_autoGeneratedDescription.isNotEmpty ? _autoGeneratedDescription : "La descripción se generará aquí..."),
                    ),
                  ),
                  const SizedBox(height: 16),

                  DropdownButtonFormField<String>(
                    value: _selectedPromotionType,
                    decoration: const InputDecoration(labelText: 'Tipo de Promoción', border: OutlineInputBorder()),
                    items: _promotionTypes.map((type) => DropdownMenuItem(value: type, child: Text(type))).toList(),
                    onChanged: (value) {
                      setState(() {
                        _selectedPromotionType = value;
                        _updateDescription();
                        _calculatePrices();
                      });
                    },
                    validator: (value) => value == null ? 'Selecciona un tipo de promoción' : null,
                  ),
                  if (_selectedPromotionType == "Otros") ...[
                    const SizedBox(height: 16),
                    TextFormField(
                      controller: _otherPromotionController,
                      decoration: const InputDecoration(labelText: 'Especifique la Promoción', border: OutlineInputBorder()),
                    ),
                  ],
                  const SizedBox(height: 16),
                  TextFormField(controller: _productController, decoration: const InputDecoration(labelText: 'Producto', border: OutlineInputBorder())),
                  const SizedBox(height: 16),
                  TextFormField(controller: _brandController, decoration: const InputDecoration(labelText: 'Marca', border: OutlineInputBorder())),
                  const SizedBox(height: 16),

                  TextFormField(controller: _storeController, decoration: const InputDecoration(labelText: 'Comercio (Tienda)', border: OutlineInputBorder())),
                  const SizedBox(height: 16),
                  TextFormField(
                    controller: _originalPriceController,
                    decoration: const InputDecoration(labelText: 'Precio Original', border: OutlineInputBorder()),
                    keyboardType: const TextInputType.numberWithOptions(decimal: true),
                    onChanged: (value) => _calculatePrices(),
                    validator: (value) => (value == null || value.isEmpty) ? 'Ingresa un precio' : null,
                  ),
                  const SizedBox(height: 16),
                  TextFormField(
                    controller: _finalPriceController,
                    decoration: const InputDecoration(labelText: 'Precio Final (con descuento)', border: OutlineInputBorder()),
                    keyboardType: const TextInputType.numberWithOptions(decimal: true),
                    onChanged: (value) => _calculatePrices(),
                    validator: (value) {
                      if (value == null || value.isEmpty) {
                        return 'Ingresa un precio final';
                      }
                      final original = double.tryParse(_originalPriceController.text);
                      final finalPrice = double.tryParse(value);
                      if (original != null && finalPrice != null && finalPrice >= original) {
                        return 'El precio final debe ser menor al original';
                      }
                      return null;
                    },
                  ),
                  const SizedBox(height: 16),
                  DropdownButtonFormField<String>(
                    value: _selectedCategory,
                    decoration: const InputDecoration(labelText: 'Categoría', border: OutlineInputBorder()),
                    items: _categories.map((category) => DropdownMenuItem(value: category, child: Text(category))).toList(),
                    onChanged: (value) => setState(() => _selectedCategory = value),
                    validator: (value) => value == null ? 'Selecciona una categoría' : null,
                  ),
                  const SizedBox(height: 24),

                  Center(
                    child: _imageFile == null ? const Text('No has seleccionado una imagen.') : Image.file(_imageFile!, height: 150),
                  ),
                  const SizedBox(height: 8),
                  ElevatedButton.icon(icon: const Icon(Icons.camera_alt), label: const Text("Tomar o Elegir Foto"), onPressed: _pickImage),
                  const SizedBox(height: 24),

                  ElevatedButton(
                    onPressed: _isLoading ? null : _submitPost,
                    style: ElevatedButton.styleFrom(padding: const EdgeInsets.symmetric(vertical: 16)),
                    child: const Text('Guardar Oferta'),
                  ),
                ],
              ),
            ),
          ),
          if (_isLoading)
            Container(
              color: Colors.black.withAlpha(128),
              child: const Center(child: CircularProgressIndicator()),
            ),
        ],
      ),
    );
  }
}
